name: remote_player_example
description: Demonstrates how to use the remote_player plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  remote_player:
    path: ../
  sqflite: ^1.1.5
  font_awesome_flutter: ^8.4.0
  shared_preferences: ^0.5.2
  flutter_spinkit: ^3.1.0
  flutter_speed_dial: ^1.1.1
  firebase_messaging: ^4.0.0+4
  firebase_analytics: ^2.1.1+3
  firebase_auth: ^0.8.4+5
#  flutter_account_kit: ^0.6.6
  flutter_html: ^0.9.6
  intro_slider: ^1.2.0
  flare_flutter: ^1.5.0
  http: ^0.12.0+2
  archive: ^2.0.8
  just_debounce_it: ^2.1.0
  qr_flutter: ^2.0.0+51
  connectivity: ^0.4.3+1
  audioplayers: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true